project_id = "uazsekwxdldlkisyvcvh"

[functions.fedapay-create-payment]
verify_jwt = true

[functions.fedapay-webhook]
verify_jwt = false

[functions.kkiapay-init]
verify_jwt = true

[functions.kkiapay-verify]
verify_jwt = true

[functions.kkiapay-webhook]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true
