/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardParentIndexRouteImport } from './routes/dashboard.parent.index'
import { Route as DashboardEncadreurIndexRouteImport } from './routes/dashboard.encadreur.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardParentPaiementsRouteImport } from './routes/dashboard.parent.paiements'
import { Route as DashboardParentCorrespondancesRouteImport } from './routes/dashboard.parent.correspondances'
import { Route as DashboardParentCatalogueRouteImport } from './routes/dashboard.parent.catalogue'
import { Route as DashboardEncadreurPaiementsRouteImport } from './routes/dashboard.encadreur.paiements'
import { Route as DashboardEncadreurCorrespondancesRouteImport } from './routes/dashboard.encadreur.correspondances'
import { Route as DashboardEncadreurCatalogueRouteImport } from './routes/dashboard.encadreur.catalogue'
import { Route as DashboardAdminValidationsRouteImport } from './routes/dashboard.admin.validations'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminPaiementsRouteImport } from './routes/dashboard.admin.paiements'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardParentIndexRoute = DashboardParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEncadreurIndexRoute = DashboardEncadreurIndexRouteImport.update({
  id: '/encadreur/',
  path: '/encadreur/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentPaiementsRoute =
  DashboardParentPaiementsRouteImport.update({
    id: '/parent/paiements',
    path: '/parent/paiements',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardParentCorrespondancesRoute =
  DashboardParentCorrespondancesRouteImport.update({
    id: '/parent/correspondances',
    path: '/parent/correspondances',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardParentCatalogueRoute =
  DashboardParentCatalogueRouteImport.update({
    id: '/parent/catalogue',
    path: '/parent/catalogue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEncadreurPaiementsRoute =
  DashboardEncadreurPaiementsRouteImport.update({
    id: '/encadreur/paiements',
    path: '/encadreur/paiements',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEncadreurCorrespondancesRoute =
  DashboardEncadreurCorrespondancesRouteImport.update({
    id: '/encadreur/correspondances',
    path: '/encadreur/correspondances',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEncadreurCatalogueRoute =
  DashboardEncadreurCatalogueRouteImport.update({
    id: '/encadreur/catalogue',
    path: '/encadreur/catalogue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminValidationsRoute =
  DashboardAdminValidationsRouteImport.update({
    id: '/admin/validations',
    path: '/admin/validations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPaiementsRoute = DashboardAdminPaiementsRouteImport.update({
  id: '/admin/paiements',
  path: '/admin/paiements',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin/paiements': typeof DashboardAdminPaiementsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/validations': typeof DashboardAdminValidationsRoute
  '/dashboard/encadreur/catalogue': typeof DashboardEncadreurCatalogueRoute
  '/dashboard/encadreur/correspondances': typeof DashboardEncadreurCorrespondancesRoute
  '/dashboard/encadreur/paiements': typeof DashboardEncadreurPaiementsRoute
  '/dashboard/parent/catalogue': typeof DashboardParentCatalogueRoute
  '/dashboard/parent/correspondances': typeof DashboardParentCorrespondancesRoute
  '/dashboard/parent/paiements': typeof DashboardParentPaiementsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/encadreur/': typeof DashboardEncadreurIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin/paiements': typeof DashboardAdminPaiementsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/validations': typeof DashboardAdminValidationsRoute
  '/dashboard/encadreur/catalogue': typeof DashboardEncadreurCatalogueRoute
  '/dashboard/encadreur/correspondances': typeof DashboardEncadreurCorrespondancesRoute
  '/dashboard/encadreur/paiements': typeof DashboardEncadreurPaiementsRoute
  '/dashboard/parent/catalogue': typeof DashboardParentCatalogueRoute
  '/dashboard/parent/correspondances': typeof DashboardParentCorrespondancesRoute
  '/dashboard/parent/paiements': typeof DashboardParentPaiementsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/encadreur': typeof DashboardEncadreurIndexRoute
  '/dashboard/parent': typeof DashboardParentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin/paiements': typeof DashboardAdminPaiementsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/validations': typeof DashboardAdminValidationsRoute
  '/dashboard/encadreur/catalogue': typeof DashboardEncadreurCatalogueRoute
  '/dashboard/encadreur/correspondances': typeof DashboardEncadreurCorrespondancesRoute
  '/dashboard/encadreur/paiements': typeof DashboardEncadreurPaiementsRoute
  '/dashboard/parent/catalogue': typeof DashboardParentCatalogueRoute
  '/dashboard/parent/correspondances': typeof DashboardParentCorrespondancesRoute
  '/dashboard/parent/paiements': typeof DashboardParentPaiementsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/encadreur/': typeof DashboardEncadreurIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/admin/paiements'
    | '/dashboard/admin/users'
    | '/dashboard/admin/validations'
    | '/dashboard/encadreur/catalogue'
    | '/dashboard/encadreur/correspondances'
    | '/dashboard/encadreur/paiements'
    | '/dashboard/parent/catalogue'
    | '/dashboard/parent/correspondances'
    | '/dashboard/parent/paiements'
    | '/dashboard/admin/'
    | '/dashboard/encadreur/'
    | '/dashboard/parent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/admin/paiements'
    | '/dashboard/admin/users'
    | '/dashboard/admin/validations'
    | '/dashboard/encadreur/catalogue'
    | '/dashboard/encadreur/correspondances'
    | '/dashboard/encadreur/paiements'
    | '/dashboard/parent/catalogue'
    | '/dashboard/parent/correspondances'
    | '/dashboard/parent/paiements'
    | '/dashboard/admin'
    | '/dashboard/encadreur'
    | '/dashboard/parent'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/admin/paiements'
    | '/dashboard/admin/users'
    | '/dashboard/admin/validations'
    | '/dashboard/encadreur/catalogue'
    | '/dashboard/encadreur/correspondances'
    | '/dashboard/encadreur/paiements'
    | '/dashboard/parent/catalogue'
    | '/dashboard/parent/correspondances'
    | '/dashboard/parent/paiements'
    | '/dashboard/admin/'
    | '/dashboard/encadreur/'
    | '/dashboard/parent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/parent/': {
      id: '/dashboard/parent/'
      path: '/parent'
      fullPath: '/dashboard/parent/'
      preLoaderRoute: typeof DashboardParentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/encadreur/': {
      id: '/dashboard/encadreur/'
      path: '/encadreur'
      fullPath: '/dashboard/encadreur/'
      preLoaderRoute: typeof DashboardEncadreurIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent/paiements': {
      id: '/dashboard/parent/paiements'
      path: '/parent/paiements'
      fullPath: '/dashboard/parent/paiements'
      preLoaderRoute: typeof DashboardParentPaiementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent/correspondances': {
      id: '/dashboard/parent/correspondances'
      path: '/parent/correspondances'
      fullPath: '/dashboard/parent/correspondances'
      preLoaderRoute: typeof DashboardParentCorrespondancesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent/catalogue': {
      id: '/dashboard/parent/catalogue'
      path: '/parent/catalogue'
      fullPath: '/dashboard/parent/catalogue'
      preLoaderRoute: typeof DashboardParentCatalogueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/encadreur/paiements': {
      id: '/dashboard/encadreur/paiements'
      path: '/encadreur/paiements'
      fullPath: '/dashboard/encadreur/paiements'
      preLoaderRoute: typeof DashboardEncadreurPaiementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/encadreur/correspondances': {
      id: '/dashboard/encadreur/correspondances'
      path: '/encadreur/correspondances'
      fullPath: '/dashboard/encadreur/correspondances'
      preLoaderRoute: typeof DashboardEncadreurCorrespondancesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/encadreur/catalogue': {
      id: '/dashboard/encadreur/catalogue'
      path: '/encadreur/catalogue'
      fullPath: '/dashboard/encadreur/catalogue'
      preLoaderRoute: typeof DashboardEncadreurCatalogueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/validations': {
      id: '/dashboard/admin/validations'
      path: '/admin/validations'
      fullPath: '/dashboard/admin/validations'
      preLoaderRoute: typeof DashboardAdminValidationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/paiements': {
      id: '/dashboard/admin/paiements'
      path: '/admin/paiements'
      fullPath: '/dashboard/admin/paiements'
      preLoaderRoute: typeof DashboardAdminPaiementsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminPaiementsRoute: typeof DashboardAdminPaiementsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminValidationsRoute: typeof DashboardAdminValidationsRoute
  DashboardEncadreurCatalogueRoute: typeof DashboardEncadreurCatalogueRoute
  DashboardEncadreurCorrespondancesRoute: typeof DashboardEncadreurCorrespondancesRoute
  DashboardEncadreurPaiementsRoute: typeof DashboardEncadreurPaiementsRoute
  DashboardParentCatalogueRoute: typeof DashboardParentCatalogueRoute
  DashboardParentCorrespondancesRoute: typeof DashboardParentCorrespondancesRoute
  DashboardParentPaiementsRoute: typeof DashboardParentPaiementsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardEncadreurIndexRoute: typeof DashboardEncadreurIndexRoute
  DashboardParentIndexRoute: typeof DashboardParentIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminPaiementsRoute: DashboardAdminPaiementsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminValidationsRoute: DashboardAdminValidationsRoute,
  DashboardEncadreurCatalogueRoute: DashboardEncadreurCatalogueRoute,
  DashboardEncadreurCorrespondancesRoute:
    DashboardEncadreurCorrespondancesRoute,
  DashboardEncadreurPaiementsRoute: DashboardEncadreurPaiementsRoute,
  DashboardParentCatalogueRoute: DashboardParentCatalogueRoute,
  DashboardParentCorrespondancesRoute: DashboardParentCorrespondancesRoute,
  DashboardParentPaiementsRoute: DashboardParentPaiementsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardEncadreurIndexRoute: DashboardEncadreurIndexRoute,
  DashboardParentIndexRoute: DashboardParentIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
